### PR TITLE
We initialize promise and reason to undefined

### PR DESCRIPTION
**Pull request by jeisinger**

### CODE REVIEW

**Comment by domenic** [comment]
This seems inconsistent with most other HTML and DOM APIs, including ErrorEvent, which use `null` as this kind of sentinel...

**Comment by jeisinger** [comment]
meh, but that requires custom bindings... anyway, will update the
implementation

**Comment by domenic** [comment]
Hmm OK, a bit surprised since things are null all over. I don't feel that strongly, but it seems best to be consistent...

Is the problem here that I need to add `?`s to the fields? `Promise<any>?` and `any? reason`? (Or maybe only the former?)

**Comment by domenic** [comment]
BTW I don't really want to require anyone to do custom bindings so happy to continue discussing until we figure this out.

**Comment by jeisinger** [comment]
already implemented... closing this request

**Comment by domenic** [comment]
Hmm OK. I am going to change it to `Promise<any>?` just to be safe.

**Pull request closed without merging**
